# Generated by Django 3.2.6 on 2021-08-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210822_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Makaleye Fotoğraf ekleyin'),
        ),
    ]
